apiVersion: v1
kind: ServiceAccount
metadata:
  name: keyvault2kube
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyvault2kube-secret-clusterrole
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keyvault2kube-secret-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: keyvault2kube
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: keyvault2kube-secret-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvault2kube
  namespace: kube-system
  labels:
    app: keyvault2kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvault2kube
  template:
    metadata:
      labels:
        app: keyvault2kube
    spec:
      serviceAccountName: keyvault2kube
      containers:
        - name: keyvault2kube
          image: terrycain/keyvault2kube:latest
