---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyvault2kube
rules:
  - apiGroups: ['']
    resources: [secrets]
    verbs: [get, update, create, patch]
  - apiGroups: ['']
    resources: [namespaces]
    verbs: [list]
