---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyvault2kube
  namespace: kube-system
  labels:
    app: keyvault2kube
spec:
  selector:
    matchLabels:
      app: keyvault2kube
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: app
      labels:
        app: keyvault2kube
        aadpodidbinding: keyvault2kube
    spec:
      serviceAccountName: keyvault2kube
      containers:
        - name: app
          image: ghcr.io/terrycain/keyvault2kube:latest
          env:
            - name: KEY_VAULT_URLS
              value: https://foo.vault.azure.net/
          securityContext:
            readOnlyRootFilesystem: true
          startupProbe:
            exec:
              command: ["test", "-f", "/tmp/done"]
            periodSeconds: 120
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 64Mi
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: tmp
          emptyDir: {}
